{
  'name': {'type': 'string', 'default': 'schema'},
  'namespace': {'type': 'string', 'default': 'core_schemas'},
  'prefix': {'type': 'string', 'default': 'schema'},
  'label': {'type': 'string', 'default': 'SCHEMA'},

  'kind': {'type': 'string', 'default': 'node'},
  
  'keys': {'type': 'list', 'required': True, 'default': ['label', 'name', 'namespace', 'body']},
  
  'props': {
    'required': True,
    'type': 'dict',
    'schema': {
      '__id': {'type': 'string', 'required': True, 'default': 'str'},
      'name': {'type': 'string', 'required': True, 'default': 'str'},
      'namespace': {'type': 'string', 'required': True, 'default': 'str'},
      'prefix': {'type': 'string', 'default': 'str'},
      'label': {'type': 'string', 'required': True, 'default': 'str'},
      'kind': {'type': 'string', 'default': 'str'},
      'body': {'type': 'string',  'required': True, 'default': 'str'},
      'url': {'type': 'string',  'required': True, 'default': 'str'}
    }
  }
}